### ISSUE TITLE
Deployment Perpetually "Not Ready"

### ISSUE THREAD

**Issue by tobiasjpark** [faas-and-furious/autocolour#4]
## Expected Behaviour

Function deploys in OpenFaaS and can be invoked.

## Current Behaviour

Function deploys in OpenFaaS but Status displays "Not Ready" and never changes to "Ready", so the function can never be invoked.

## Steps to Reproduce (for bugs)

1. Clone the repo
2. Add your user name to the image fields in the yaml files so you can push to Docker
3. Run `faas-cli up -f stack.yml`
4. View the function in the OpenFaaS UI Portal

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):
CLI:
 commit:  5fcdc692e4adf04977775ea78f79b3534a44fb36
 version: 0.8.21

* Docker version `docker version` (e.g. Docker 18.06 ):
18.09.8

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Kubernetes

* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 18.04.2

* How much RAM is available on your nodes?
64 GB

* Are you running on x86_64 or ARM?
x86_64

* Link to your project or a code example to reproduce issue:
https://github.com/faas-and-furious/autocolour

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by alexellis** [comment]
Hi

This needs rebuilding / pushing by myself.

You can however use `normalisecolor` from `faas-cli store list/deploy` in the time-being.

Alex

--
Join Slack to connect with the community
https://docs.openfaas.com

**Comment by alexellis** [comment]
I've overwritten the existing images and pushed them again. You can try again now.

Alex

**Comment by alexellis** [comment]
By the way - thanks a lot for filling in the template properly, that really helped.
